catalog/urls.py
from django.urls import path

from catalog.views import (index,
                           LiteraryFormatListView,
                           LiteraryFormatCreateView,
                           LiteraryFormatUpdateView,
                           LiteraryFormatDeleteView,

                           BookListView,
                           # book_detail_view,
                           BookDetailView,
                           BookCreateView,
                           BookUpdateView,

                            # test_session_view,
                            AuthorListView,
                            AuthorDetailView,
                            AuthorCreateView,
                           )

urlpatterns = [
    path("", index, name="index" ),
    #path("literary-formats/", literary_format_list_view, name="literary-formats-list"),


    path("literary-formats/", LiteraryFormatListView.as_view(), name="literary-format-list"),
    path("literary-formats/create/", LiteraryFormatCreateView.as_view(), name="literary-format-create"),
    path("literary-formats/<int:pk>/update/", LiteraryFormatUpdateView.as_view(), name="literary-format-update"),
    path("literary-formats/<int:pk>/delete/", LiteraryFormatDeleteView.as_view(), name="literary-format-delete"),

    path("books/", BookListView.as_view(), name="book-list"),
    path("books/create/", BookCreateView.as_view(), name="book-create"),
    # path("books/<int:pk>/", book_detail_view, name="book-detail"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("books/<int:pk>/update/", BookUpdateView.as_view(), name="book-update"),


    # path("test-session", test_session_view, name="test-session"),

    path("authors/", AuthorListView.as_view(), name="author-list"),
    path("authors/create/", AuthorCreateView.as_view(), name="author-create"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),
]

app_name = "catalog"

library/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    # path("catalog/", include("catalog.urls", namespace="catalog")),
    path("", include("catalog.urls", namespace="catalog")), # таким чином, рибравши catalog/, всі запити в корень нашого пролекту будуть потряпляти на домашню сторінку
    #path("registration/", include("registration.urls", namespace="registration")), - це кастомний path для автентифікації користувача
    path("accounts/", include("django.contrib.auth.urls")),# - це стандартний path для автентифікації користувача
] + debug_toolbar_urls()

templates/includes/pagination.html
{% load query_transform %}
{% block pagination %}
          {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}">Prev</a>
              </li>
            {% endif %}
            <li class="page-item active">
              <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
            </li>
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">Next</a>
              </li>
            {% endif %}
          </ul>
          {% endif %}
{% endblock %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">

  {%  if user.is_authenticated %}
    <li class="list-group-item">
      User: {{ user.username }}
    </li>
    <li class="list-group-item">
      <a href="{% url 'logout' %}">Logout</a>
    </li>
  {% else %}
    <li class="list-group-item">
      <a href="{% url 'login' %}">Login</a>
    </li>
  {% endif %}
  <br>
  <li class="list-group-item">
    <a href="{% url 'catalog:index' %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'catalog:author-list' %}">All authors</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'catalog:book-list' %}">All books</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'catalog:literary-format-list' %}">All literary formats</a>
  </li>
</ul>