catalog/urls.py
from django.urls import path

from catalog.views import (index,
                           LiteraryFormatListView,
                           LiteraryFormatCreateView,
                           LiteraryFormatUpdateView,
                           LiteraryFormatDeleteView,

                           BookListView,
                           # book_detail_view,
                           BookDetailView,
                           BookCreateView,
                           BookUpdateView,

                            # test_session_view,
                            AuthorListView,
                            AuthorDetailView,
                            AuthorCreateView,
                           )

urlpatterns = [
    path("", index, name="index" ),
    #path("literary-formats/", literary_format_list_view, name="literary-formats-list"),


    path("literary-formats/", LiteraryFormatListView.as_view(), name="literary-format-list"),
    path("literary-formats/create/", LiteraryFormatCreateView.as_view(), name="literary-format-create"),
    path("literary-formats/<int:pk>/update/", LiteraryFormatUpdateView.as_view(), name="literary-format-update"),
    path("literary-formats/<int:pk>/delete/", LiteraryFormatDeleteView.as_view(), name="literary-format-delete"),

    path("books/", BookListView.as_view(), name="book-list"),
    path("books/create/", BookCreateView.as_view(), name="book-create"),
    # path("books/<int:pk>/", book_detail_view, name="book-detail"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("books/<int:pk>/update/", BookUpdateView.as_view(), name="book-update"),


    # path("test-session", test_session_view, name="test-session"),

    path("authors/", AuthorListView.as_view(), name="author-list"),
    path("authors/create/", AuthorCreateView.as_view(), name="author-create"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),
]

app_name = "catalog"

library/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    # path("catalog/", include("catalog.urls", namespace="catalog")),
    path("", include("catalog.urls", namespace="catalog")), # таким чином, рибравши catalog/, всі запити в корень нашого пролекту будуть потряпляти на домашню сторінку
    #path("registration/", include("registration.urls", namespace="registration")), - це кастомний path для автентифікації користувача
    path("accounts/", include("django.contrib.auth.urls")),# - це стандартний path для автентифікації користувача
] + debug_toolbar_urls()

catalog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class LiteraryFormat(models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        ordering = ('name', )# сортування в БД за 'name'

    def __str__(self):
        return self.name


class Author(AbstractUser):
    pseudonym = models.CharField(max_length=63, null=True, blank=True)

    class Meta:
        ordering = ("username", )# сортування по полю "username"

    def __str__(self):
        return f"{self.username}: {self.first_name} {self.last_name}"# щоб відображалось більш інформативно в полі authors при створенні Book в адмінпанелі

    def get_absolute_url(self):
        return reverse("catalog:author-detail", args=[str(self.id)])


class Book(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(
        max_digits=7,
        decimal_places=2
    )
    format = models.ForeignKey(
        LiteraryFormat,
        on_delete=models.CASCADE,
        related_name="books"
    )
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="books")

    class Meta:
        ordering = ("title", )# сортування за "title"

    def __str__(self):
        return f"{self.title} (price: {self.price}), format: {self.format.name}"

    def get_absolute_url(self):
        return reverse("catalog:book-detail", args=[str(self.id)])

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from catalog.models import Author, Book


class AuthorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Author
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "pseudonym",)


class BookForm(forms.ModelForm):
    authors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )                                           # тут required=False означає, що можна створити книгу без автора
    class Meta:
        model = Book
        fields = "__all__"


class BookSearchForm(forms.Form):              # наслідування не від ModelForm, а від Form, оскільки цей клас не буде взаємодіяти на пряму з моделями
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by Title"}),
    )

catalog/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import AuthorCreationForm, BookForm, BookSearchForm
from .models import Book, Author, LiteraryFormat


@login_required# цей декоратор забороняє потрапляти на головну сторінку (Home) не залогіненим користувачам, але він працює лише з FBV (function base view)
def index(request: HttpRequest) -> HttpResponse:
    # now = datetime.datetime.now()
    #print(f"Request params: {request.GET}")
    num_books = Book.objects.all().count()
    num_authors = Author.objects.count()
    num_literary_formats = LiteraryFormat.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'key_num_books': num_books,
        "key_num_authors": num_authors,
        "key_num_literary_formats": num_literary_formats,
        "num_visits": num_visits + 1,
    }
    return render(
        request,
        "catalog/index.html",
        context=context
    )



# def literary_format_list_view(request: HttpRequest) -> HttpResponse:
#     literary_formats_list = LiteraryFormat.objects.all()
#     context = {
#         'key_literary_formats_list': literary_formats_list,
#     }
#     return render(
#         request,
#         "catalog/literary_format_list.html",
#         context=context
#     )


class LiteraryFormatListView(LoginRequiredMixin, generic.ListView):# для заборони потрапляння не залогіненим користувачам в CBV (Class Base View) використовуються міксини
    model = LiteraryFormat
    template_name = "catalog/literary_format_list.html"
    context_object_name = "key_literary_formats_list"
    paginate_by = 4


class LiteraryFormatCreateView(LoginRequiredMixin, generic.CreateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-format-list")# на цю адресу користувача буде редіректити після заповнення форми
    template_name = "catalog/literary_format_form.html"# в цьому випадку (при створенні) форма для заповнення буде пуста


class LiteraryFormatUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-format-list")#на цю адресу користувача буде редіректити після заповнення форми
    template_name = "catalog/literary_format_form.html"# в цьому випадку (при оновленні) форма буде вже заповнена


class LiteraryFormatDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_confirm_delete.html"
    success_url = reverse_lazy("catalog:literary-format-list")


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    # queryset = Book.objects.select_related("format")
    paginate_by = 2

    # додаємо опцію, щоб введений текст зберігався. Для цього треба змінити метод:
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = BookSearchForm(
            initial={"title": title},
        )
        return context

    # # реалізуємо пошук за допомогою пошукового слова title. Для цього треба змінити метод:
    # def get_queryset(self):
    #     title = self.request.GET.get("title", "")
    #     if title:
    #         return self.queryset.filter(title__icontains=title)
    #     return self.queryset


# реалізуємо пошук за допомогою створеною нами форми BookSearchForm. Для цього треба змінити метод:
    def get_queryset(self):
        queryset = Book.objects.select_related("format")
        form = BookSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])
        return queryset


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    paginate_by = 3


# def book_detail_view(request: HttpRequest, pk: int) -> HttpResponse:
#     try:
#         book = Book.objects.get(id=pk)
#     except Book.DoesNotExist:
#         raise Http404("Book does not exist")
#
#     context = {
#         "key_book": book,
#     }
#     return render(request, "catalog/book_detail.html", context=context)


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class BookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Book
    # fields = "__all__"
    form_class = BookForm


class BookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Book
    form_class = BookForm


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author


class AuthorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Author
    form_class = AuthorCreationForm
    # template_name = "catalog/author_form.html"




# def test_session_view(request: HttpRequest) -> HttpResponse:
#     return HttpResponse(
#         "<h1>Test Session</h1>"
#         f"<h4>Session Data: {request.session['book']}</h4>"
#     )

templates/catalog/author_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ author.first_name }}{{ author.last_name }}</h1>
  <p><strong>username: </strong>{{ author.username }}</p>
  <p><strong>Pseudonym: </strong>{{ author.pseudonym }}</p>
  <p><strong>Is staff: </strong>{{ author.is_staff }}</p>
  <div class="ml-3">
    <h3>Books:</h3>
    {% for book in author.books.all %}
      <hr>
      <p class="text-muted">id: {{ book.id }}</p>
      <p><strong>Title: {{ book.title }}</strong></p>
      <p><strong>Format: {{ book.format }}</strong></p>
    {% empty %}
      <p>No books!</p>
    {% endfor %}

  </div>
{% endblock %}

templates/catalog/author_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>Create Author</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/author_list.html
{% extends "base.html" %}
{% block content %}
  <h1>Author List<a class="btn btn-secondary" style="float: right" href="{% url 'catalog:author-create' %}">+</a></h1>
  <ul>
    {% if author_list %}
      {% for author in author_list %}
        <li>
          <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }} ({{ author.pseudonym }}, {{ author.username }})</a>
        </li>
      {% endfor %}
    {% endif %}
  </ul>
{% endblock %}

templates/catalog/book_detail.html
{% extends "base.html" %}

{#Скрипт для кастомної ф-ції book_detail_view (function base view)#}
{#т.я. в context = {"key_book": book,}#}

{#{% block content %}#}
{#  <h1>Title: {{ key_book.title }}</h1>#}
{#  <p><strong>Price: </strong>{{ key_book.price }}</p>#}
{#  <p><strong>Format: </strong>{{ key_book.format }}</p>#}
{#  <div class="ml-3">#}
{#    <h3>Authors:</h3>#}
{#    {% for author in key_book.authors.all %}#}
{#      <hr>#}
{#      <p class="text-muted">{{ author.id }}</p>#}
{#      <p>{{ author.first_name }} {{ author.last_name }}#}
{#        {% if author.pseudonym %}#}
{#          {{ author.pseudonym }}#}
{#        {% endif %}#}
{#      </p>#}
{#    {% empty %}#}
{#      <p>No authors!</p>#}
{#    {% endfor %}#}
{#  </div>#}
{##}
{#{% endblock %}#}


{#Скрипт для class BookDetailView, тому що Gjango в context бачить "book" замівть "key_book"#}

{% block content %}
  <h1>Title: {{ book.title }}<a class="btn btn-secondary" style="float: right" href="{% url 'catalog:book-update' pk=book.id %}">Edit</a></h1>
  <p><strong>Price: </strong>{{ book.price }}</p>
  <p><strong>Format: </strong>{{ book.format }}</p>
  <div class="ml-3">
    <h3>Authors:</h3>
    {% for author in book.authors.all %}
      <hr>
      <p class="text-muted">{{ author.id }}</p>
      <p>{{ author.first_name }} {{ author.last_name }}
        {% if author.pseudonym %}
          {{ author.pseudonym }}
        {% endif %}
      </p>
    {% empty %}
      <p>No authors!</p>
    {% endfor %}
  </div>

{% endblock %}

templates/catalog/book_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Book</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/book_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Book List<a class="btn btn-secondary" style="float: right" href="{% url 'catalog:book-create' %}">+</a></h1>
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="Submit">
  </form>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }} ({{ book.price }}, {{ book.format }})</a>
      </li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}

{% block title %}
  <title>Home page</title>
{% endblock %}

{% block content %}
  <h1>Library Home</h1>
  <p>Welcome to the Greatest Library!</p>
  <h3>Library content:</h3>
  <ul>
    <li>Num books: {{ key_num_books }}</li>
    <li>Num authors: {{ key_num_authors }}</li>
    <li>Num literary formats: {{ key_num_literary_formats }}</li>
  </ul>
  <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
{% endblock %}

templates/catalog/literary_format_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Literary Format</h1>
  <p>Are you sure you want to delete the literary format: {{ literaryformat.name }}?</p>
  <p><i>All Books with this literary format will be also deleted!</i></p>
  <form action="", method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/catalog/literary_format_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Literary Format</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/literary_format_list.html
{#{% extends "base.html" %}#}
{#{% block content %}#}
{#  <h1>Literary Format List<a style="float: right" href="{% url 'catalog:literary-format-create' %}"> + Create</a></h1>#}
{#  {% if key_literary_formats_list %}#}
{#        <ul>#}
{#          {% for literary_format in key_literary_formats_list %}#}
{#            <li>{{ literary_format.name }}</li>#}
{#          {% endfor %}#}
{#        </ul>#}
{#  {% else %}#}
{#        <p>There are no Literary formats in Library</p>#}
{#  {% endif %}#}
{#{% endblock %}#}


{% extends "base.html" %}

{% block content %}
  <h1>Literary Format List<a class="btn btn-secondary" style="float: right" href="{% url 'catalog:literary-format-create' %}">+</a></h1>

  {% if key_literary_formats_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for literary_format in key_literary_formats_list %}
        <tr>
          <td>
            {{ literary_format.id }}
          </td>
          <td>
            {{ literary_format.name }}
          </td>
          <td>
            <a href="{% url 'catalog:literary-format-update' pk=literary_format.id %}">UPDATE</a>
          </td>
          <td>
            <a href="{% url 'catalog:literary-format-delete' pk=literary_format.id %}">DELETE</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no Literary formats in Library</p>
  {% endif %}
{% endblock %}